# Generated by Django 6.0.1 on 2026-01-14 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000, verbose_name='Оригинальный URL')),
                ('short_code', models.CharField(max_length=20, unique=True, verbose_name='Короткий код')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название ссылки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Кликов')),
                ('last_clicked', models.DateTimeField(blank=True, null=True, verbose_name='Последний клик')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='Пароль (опционально)')),
                ('is_private', models.BooleanField(default=False, verbose_name='Приватная ссылка')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Теги (через запятую)')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR код')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortened_urls', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сокращенная ссылка',
                'verbose_name_plural': 'Сокращенные ссылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Клики')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Уникальные посетители')),
                ('desktop_clicks', models.PositiveIntegerField(default=0, verbose_name='Клики с десктопов')),
                ('mobile_clicks', models.PositiveIntegerField(default=0, verbose_name='Клики с мобильных')),
                ('tablet_clicks', models.PositiveIntegerField(default=0, verbose_name='Клики с планшетов')),
                ('top_countries', models.JSONField(default=dict, verbose_name='Топ стран')),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='shortener.shortenedurl', verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Ежедневная статистика',
                'verbose_name_plural': 'Ежедневная статистика',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClickStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Время клика')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, max_length=1000, verbose_name='Реферер')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('device_type', models.CharField(choices=[('desktop', 'Десктоп'), ('mobile', 'Мобильный'), ('tablet', 'Планшет'), ('bot', 'Бот'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип устройства')),
                ('browser', models.CharField(choices=[('chrome', 'Chrome'), ('firefox', 'Firefox'), ('safari', 'Safari'), ('edge', 'Edge'), ('opera', 'Opera'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Браузер')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='ОС')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Бот')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID сессии')),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shortenedurl', verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Статистика клика',
                'verbose_name_plural': 'Статистика кликов',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('website', models.URLField(blank=True, verbose_name='Вебсайт')),
                ('default_link_expiry_days', models.IntegerField(default=30, verbose_name='Срок действия ссылок по умолчанию')),
                ('show_advanced_options', models.BooleanField(default=False, verbose_name='Показывать расширенные настройки')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная'), ('auto', 'Авто')], default='light', max_length=20, verbose_name='Тема')),
                ('total_clicks', models.PositiveIntegerField(default=0, verbose_name='Всего кликов')),
                ('total_links', models.PositiveIntegerField(default=0, verbose_name='Всего ссылок')),
                ('api_key', models.CharField(blank=True, max_length=64, verbose_name='API ключ')),
                ('api_usage', models.PositiveIntegerField(default=0, verbose_name='Использование API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['short_code'], name='shortener_s_short_c_f1ca7f_idx'),
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['user', 'created_at'], name='shortener_s_user_id_b23453_idx'),
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['is_active', 'expires_at'], name='shortener_s_is_acti_3ffe01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailystats',
            unique_together={('shortened_url', 'date')},
        ),
        migrations.AddIndex(
            model_name='clickstatistics',
            index=models.Index(fields=['shortened_url', 'clicked_at'], name='shortener_c_shorten_0e9125_idx'),
        ),
        migrations.AddIndex(
            model_name='clickstatistics',
            index=models.Index(fields=['country', 'city'], name='shortener_c_country_e98a59_idx'),
        ),
        migrations.AddIndex(
            model_name='clickstatistics',
            index=models.Index(fields=['device_type', 'browser'], name='shortener_c_device__65669b_idx'),
        ),
    ]
